language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies, no dependencies required at the moment
 install: 
  - apt-get install python-dev
# command to run tests
script: nosetests